appName: checkoutservice
replicaCount: 1
image:
  repository: gcr.io/google-samples/microservices-demo/checkoutservice
  tag: v0.2.3
containerPort: 5050
serviceType: ClusterIP
servicePort: 5050
containerVars:
- key: PORT
  value: "5050"
- key: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- key: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- key: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- key: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- key: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- key: CART_SERVICE_ADDR
  value: "cartservice:7070"