appName: frontend
replicaCount: 1
image:
  repository: gcr.io/google-samples/microservices-demo/frontend
  tag: v0.2.3
containerPort: 8080
serviceType: ClusterIP
servicePort: 8099
containerVars:
- key: PORT
  value: "8080"
- key: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- key: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- key: CART_SERVICE_ADDR
  value: "cartservice:7070"
- key: RECOMMENDATION_SERVICE_ADDR
  value: "recommendationservice:8080"
- key: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- key: CHECKOUT_SERVICE_ADDR
  value: "checkoutservice:5050"
- key: AD_SERVICE_ADDR
  value: "adservice:9555"